public class FortressShield : EquipmentItem {


    public FortressShield()
    {
        this.name = "Fortress Shield";
        this.description = "Start each turn with Block equal to the amount generated by your Defend action.";
        this.slot = ActionType.DEFEND;
        this.price = 260;
        this.tier = 3;
    }

    // Gain block
    public override void startOfTurn() {
        if(this.parentAction != null && this.parentAction.owner != null && this.parentAction.block > 0) {
            if(this.parentAction.owner != null) {
                Console.WriteLine("Fortress Shield blocked for "+this.parentAction.block+".");
                // Generate Block.
                Battlefield.addBlock(this.parentAction.block, this.parentAction.owner);    
            }
        }
    }

}