public class FortressShield : EquipmentItem {


    public FortressShield() {
        this.name = "Fortress Shield";
        this.description = "Start each turn with Block equal to the amount generated by your Defend action.";
        this.slot = ActionType.DEFEND;
        this.price = 260;
    }

    // Gain block
    public override void startOfTurn() {
        if(this.parentAction != null && this.parentAction.block > 0) {
            int shieldAmount = this.parentAction.block;
            if(this.parentAction.owner != null) {
                Console.WriteLine("Fortress Shield blocked for "+shieldAmount+".");
                // Generate Block.
                Battlefield.addBlock(shieldAmount, (this.parentAction.owner!.playerControlled));    
            }
        }
    }

}