public class ReinforcedMod : Modifier {

    public ReinforcedMod()
    {
        this.name = "Reinforced";
        this.description = "Increases the block generated by the action by 1.";
        this.blockMod = 1;
    }

}